app = "bc-redis-cache"
primary_region = "lax"
swap_size_mb = 1024

#[mounts]
#  destination = "/data"
#  source = "bc_redis_cache_data"

[metrics]
  port = 9091
  path = "/metrics"

# Use the Docker image instead of building from source

[build]
  dockerfile = "Dockerfile"
  [build.args]
    ENV = "production"
    REDIS_VERSION = "8.2"

[env]
  ENV = "production"
  APPENDONLY="yes"
  MAXMEMORY_POLICY="allkeys-lru"
  FLY_VM_MEMORY_MB="256"

# Uncomment these lines for public internet access to Redis on port 10000
#
# [[services]]
# internal_port = 6379
# protocol      = "tcp"

#   [[services.ports]]
#   port     = "10000"

#   [[services.tcp_checks]]
#   interval = 10000
#   timeout  = 2000
